cabal-version:      3.14
name:               mc-config
version:            0.2.0.0
-- synopsis:
-- description:
license:            MIT
license-file:       LICENSE
author:             ruzen42
maintainer:         malledeferlive@gmail.com
-- copyright:
category:           Control
build-type:         Simple
extra-doc-files:    CHANGELOG.md
-- extra-source-files:

common warnings
    ghc-options: -Wall

executable mc-config
    import:           warnings
    main-is:          Main.hs
    other-modules:
      Config
      Install
      Tmux
      Logger
    -- other-extensions:
    build-depends:    base
                    , directory
                    , aeson
                    , aeson-pretty
                    , bytestring
                    , process
                    , wreq
                    , lens
                    , directory
                    , optparse-applicative
                    , rainbow
    hs-source-dirs:   app
    default-language: GHC2024
